language: php

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

sudo: false

install:
  - export AWS_ACCESS_KEY_ID=foo
  - export AWS_SECRET_ACCESS_KEY=bar
  - travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit --colors --testsuite=unit
