language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
- export AWS_ACCESS_KEY_ID=foo
- export AWS_SECRET_ACCESS_KEY=bar
- composer self-update
- composer install --no-interaction --prefer-source

script: make travis

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
