language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - sh -c 'if [ $(php -r "echo PHP_MINOR_VERSION;") -le 4 ]; then echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;' || true
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script: vendor/bin/phpunit
