language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_script:
- echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- cp test_services.json.dist test_services.json
- composer install --dev
script: vendor/bin/phpunit
