language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

env:
- AWS_ACCESS_KEY_ID=foo
- AWS_SECRET_ACCESS_KEY=bar

script: make travis

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true
